name: GodsEyeReplay
version: ${project.version}
api-version: 1.13
main: com.nort721.replay.GEReplay
author: Nort721
description: Records players that trigger GodsEye alerts
depend: [ GodsEye ]
softdepend: [ AdvancedReplay, ShadowSnap  ]

commands:
  gereplay:
    description: Base command
    usage: /<command> help
    aliases: [ gr ]